name: CD - Deploy Strapi via CodeDeploy

on:
  workflow_run:
    workflows: ["CI - Build & Push Strapi Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Render ECS task definition
        run: |
          sed "s|IMAGE_URI|docker.io/${{ secrets.DOCKERHUB_USERNAME }}/strapi:${{ github.event.workflow_run.head_sha }}|" \
          appspec/taskdef.json > taskdef-rendered.json

      - name: Register ECS task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://taskdef-rendered.json

      - name: Create CodeDeploy revision file
        run: |
          cat <<EOF > revision.json
          {
            "revisionType": "AppSpecContent",
            "appSpecContent": {
              "content": "$(base64 -w 0 appspec/appspec.yaml)"
            }
          }
          EOF

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name strapi-codedeploy-app \
            --deployment-group-name strapi-blue-green \
            --revision file://revision.json
